### ISSUE TITLE
cannot custom dot widget anymore

### ISSUE THREAD

**Issue by artoriazz** [RajnishOnly/another_stepper#10] opened 2022-11-25 19:16 UTC
![image](https://user-images.githubusercontent.com/111276977/204043729-7de912dc-7428-4aa6-9998-a41986dd8422.png)
I am trying to custom stepper with another icon and color but look like dotWidget removed from your plugin. Is there another way to do it?
Another question, how to make vertical stepper scrollable inside singlechildscroll?

**Comment by RajnishOnly** [comment] 2022-11-25 19:49
1. Yes, we have removed it from `AnotherWidget` widget. Its is moved to `StepperData`. 

Now you can add `iconWidget` for each stepper.

2. For scrolling vertical stepper in singleChildScrollView you need to give physics in `scrollPhysis` parameter in `AnotherStepper` as `AlwaysScrollablePhysics`.

**Comment by RajnishOnly** [comment] 2022-11-25 21:55
Closing this issue. As the problem is solved.

**Closed** 2022-11-25 21:56 UTC
