### ISSUE TITLE
allow default color change for inactive iconWidget in StepperData

### ISSUE THREAD

**Issue by michealgabriel** [RajnishOnly/another_stepper#15] opened 2023-02-11 01:33 UTC
Hi @RajnishOnly, I'm micheal.
I love your package, by the way, it's really smooth ❤️

I have a request:
- please allow background color definition for iconWidget property when it's inactive.
- I cannot change the default color, it's a deep grey that does not quite blend with my app design.

Thanks. Much love from Nigeria.

**Comment by RajnishOnly** [comment] 2023-02-11 07:51
Hey @michealgabriel 
Thanks for using my package.

I got your issue. Can you share a screenshot for better understanding?
I will create a new release soon!

**Comment by michealgabriel** [comment] 2023-02-11 10:12
Thanks for the swift response!

This is what I have: 

- ![app shot](https://user-images.githubusercontent.com/99659402/218252222-48541f7e-6430-4133-a691-38468b0b5f69.jpg)


- Code setup
![another stepper](https://user-images.githubusercontent.com/99659402/218252253-62de471d-6ae4-4ec4-bba5-cd3dc373ec2c.png)

- The stepper data list:
![stepper data list](https://user-images.githubusercontent.com/99659402/218252267-b9513b5b-7556-47e3-a7dd-ca4d71f63af0.png)

- I'm not sure if I'm missing something, but I cannot seem to get rid of those greys
- The above ones in purple are also grey when inactive

BTW - I really hope my explanation is clear, I'm a bit nooby 😁

**Comment by RajnishOnly** [comment] 2023-02-11 10:48
Got the issue, fixing it!
Will release it at the earliest..

Thank you for bringing it to my notice.

**Comment by michealgabriel** [comment] 2023-02-11 11:09
That's awesome, great work!

Thanks a lot.

**Comment by RajnishOnly** [comment] 2023-02-11 11:12
The update is released!
Please use another_stepper: ^1.2.0.

**Comment by RajnishOnly** [comment] 2023-02-11 11:12
Closing this issue, as the problem is solved.

**Closed by RajnishOnly** 2023-02-11 11:12 UTC
Labels: bug
